//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ContactType
    {
        public ContactType()
        {
            this.PersonContacts = new HashSet<PersonContact>();
        }
    
        public int ContactTypeKey { get; set; }
        public string ContactTypeName { get; set; }
    
        public virtual ICollection<PersonContact> PersonContacts { get; set; }
    }
}
