//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class EmployeeJobTitle
    {
        public int EmployeeJobTitleKey { get; set; }
        public Nullable<int> JobTitleKey { get; set; }
        public Nullable<System.DateTime> JobTitleAssignedDate { get; set; }
        public Nullable<System.DateTime> JobTitleEndDate { get; set; }
        public Nullable<int> EmployeeKey { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual Jobtitle Jobtitle { get; set; }
    }
}
