//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class Employee
    {
        public Employee()
        {
            this.Donations = new HashSet<Donation>();
            this.EmployeeJobTitles = new HashSet<EmployeeJobTitle>();
            this.ServiceGrants = new HashSet<ServiceGrant>();
            this.GrantReviews = new HashSet<GrantReview>();
        }
    
        public int EmployeeKey { get; set; }
        public Nullable<System.DateTime> EmployeeHireDate { get; set; }
        public string EmployeeSSNumber { get; set; }
        public Nullable<int> EmployeeDependents { get; set; }
        public Nullable<int> PersonKey { get; set; }
        public string EmployeeStatus { get; set; }
        public Nullable<decimal> EmployeeMonthlySalary { get; set; }
    
        public virtual ICollection<Donation> Donations { get; set; }
        public virtual Person Person { get; set; }
        public virtual ICollection<EmployeeJobTitle> EmployeeJobTitles { get; set; }
        public virtual ICollection<ServiceGrant> ServiceGrants { get; set; }
        public virtual ICollection<GrantReview> GrantReviews { get; set; }
    }
}
