//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class GrantReview
    {
        public int GrantReviewNotesKey { get; set; }
        public Nullable<System.DateTime> GrantReviewDate { get; set; }
        public Nullable<int> EmployeeKey { get; set; }
        public Nullable<int> GrantKey { get; set; }
        public string GrantReviewNote { get; set; }
    
        public virtual Employee Employee { get; set; }
        public virtual ServiceGrant ServiceGrant { get; set; }
    }
}
