//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PersonAddress
    {
        public int PersonAddressKey { get; set; }
        public string Street { get; set; }
        public string Apartment { get; set; }
        public string State { get; set; }
        public string City { get; set; }
        public string Zip { get; set; }
        public Nullable<int> PersonKey { get; set; }
    
        public virtual Person Person { get; set; }
    }
}
