//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace MVCTestApp.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ServiceGrant
    {
        public ServiceGrant()
        {
            this.GrantReviews = new HashSet<GrantReview>();
        }
    
        public int GrantKey { get; set; }
        public Nullable<decimal> GrantAmount { get; set; }
        public Nullable<System.DateTime> GrantDate { get; set; }
        public Nullable<int> PersonKey { get; set; }
        public Nullable<int> ServiceKey { get; set; }
        public Nullable<int> EmployeeKey { get; set; }
        public Nullable<System.DateTime> GrantReviewDate { get; set; }
        public string GrantApprovalStatus { get; set; }
        public string GrantNeedExplanation { get; set; }
        public Nullable<decimal> GrantAllocation { get; set; }
    
        public virtual CommunityService CommunityService { get; set; }
        public virtual Employee Employee { get; set; }
        public virtual ICollection<GrantReview> GrantReviews { get; set; }
        public virtual Person Person { get; set; }
    }
}
